language: java
notifications:
  irc:
    channels:
      - "chat.freenode.net#mosstest"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
